services:
  walk-map-api:
    build: .
    container_name: walk-map-api
    restart: unless-stopped
    env_file:
      - path: .env
        required: true
    volumes:
      - walk-map-api-data:/app/data
    ports:
      - "127.0.0.1:8103:8000"

volumes:
  walk-map-api-data: